-- Add "Wedding shower" to the special event categories.
--
-- The category check was declared inline in the member portal migration, so
-- its name was generated by Postgres. Drop whatever check mentions category
-- and add a named one with the new value.

do $$
declare
  c record;
begin
  for c in
    select con.conname
    from pg_constraint con
    where con.conrelid = 'public.special_events'::regclass
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%category%'
  loop
    execute format('alter table public.special_events drop constraint %I', c.conname);
  end loop;
end
$$;

alter table public.special_events
  add constraint special_events_category_check
    check (category is null or category in (
      'baby_shower', 'wedding_shower', 'meal_train', 'birthday', 'gospel_meeting', 'fellowship', 'service_project', 'other'
    ));
